vairaden/pixel-punch-game

packages/client/jest.config.js
packages/client/package.json
packages/client/src/app/App/App.tsx
packages/client/src/app/style/root.scss
packages/client/src/pages/RegistrationPage/RegistrationPage.tsx
packages/client/src/pages/RegistrationPage/index.ts
yarn.lock

PIX-19 Сверстать страницу регистрации
Добавить валидацию

PIX-19 Сверстать страницу регистрации

---

packages/client/src/pages/LoginPage/LoginPage.tsx
packages/client/src/pages/LoginPage/index.ts

PIX-15 Вёрстка страницы логина
Добавить переход на страницу регистрации

PIX-15 Вёрстка страницы логина

---

packages/client/src/app/App/App.tsx
packages/client/src/app/providers/index.ts
packages/client/src/app/providers/router/index.ts
packages/client/src/app/providers/router/routes.tsx

Отображение страниц, используя React Router и React Router DOM
- В проект подключён react-router 
- Все валидные роуты отображают контент (или заглушки). 
- Невалидный роут ведёт на страницу 404.

PIX-11 Отображение страниц, используя React Router и React Router DOM

---

packages/client/src/app/providers/router/routes.tsx
packages/client/src/pages/ErrorPage/ErrorPage.tsx
packages/client/src/pages/ErrorPage/index.ts

Вёрстка страницы ошибок 400
- Страница свёрстана.
- Добавлен роут.

PIX-13 Вёрстка страницы ошибок 400

---

packages/client/src/app/providers/router/routes.tsx

Вёрстка страницы ошибок 500
- Страница свёрстана.
- Добавлен роут.

PIX 14 Вёрстка страницы ошибок 500

---

packages/client/src/app/App/App.tsx
packages/client/src/app/constants/paths.ts
packages/client/src/app/providers/router/AuthGuard.tsx
packages/client/src/app/providers/router/routes.tsx
packages/client/src/pages/LoginPage/LoginPage.tsx
packages/client/src/pages/RegistrationPage/RegistrationPage.tsx
packages/client/src/shared/api/authApi.ts
packages/client/src/shared/api/baseApi.ts
packages/client/src/shared/api/testApi.ts
packages/client/src/shared/store/store.ts
packages/client/src/shared/types.ts
yarn.lock

PIX-16 Реализовать логику авторизации

PIX-16 Реализовать логику авторизации

---

packages/client/src/app/providers/errorBoundary/ErrorBoundary.tsx
packages/client/src/app/providers/errorBoundary/index.ts
packages/client/src/app/providers/index.ts
packages/client/src/app/providers/router/routes.tsx
packages/client/src/pages/ErrorPage/ErrorPage.tsx

PIX-25 Настроить обработку ошибок внутри «детей» React-компонентов

PIX-25 Настроить обработку ошибок внутри «детей» React-компонентов

---

packages/client/src/widgets/Game/Game.tsx

PIX-32 Добавить минимум одно Web API

---

packages/client/src/app/providers/router/withAuthGuard.tsx
packages/client/src/features/Profile/model/selectors.ts
packages/client/src/features/Profile/ui/ProfileAvatar.tsx
packages/client/src/features/Profile/ui/ProfileInfo.tsx
packages/client/src/shared/api/profileApi.ts
packages/client/src/shared/hooks/useActions.ts
packages/client/src/shared/store/index.ts
packages/client/src/shared/store/slices/user.slice.ts
packages/client/src/shared/store/store.ts

Добавить Redux-хранилище: - данные хранятся и обрабатываются через Redux; - состояния приложения хранятся в сторе

PIX-33 Добавить Redux-хранилище

---

packages/client/src/app/index.tsx
packages/client/src/shared/utils/serviceWorker.ts
packages/client/sw.js
packages/client/vite.config.ts

Добавить Service Workers
Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета — не только элементы входа и пользовательские настройки, но и сама игра. Допускается использование плагинов для создания конфигурации воркера, но сам функционал требуется написать самостоятельно в соответствии с материалами из уроков.

PIX-30 Добавить Service Workers

---

packages/client/index.html
packages/client/package.json
packages/client/src/app/MockPage.tsx
packages/client/src/app/index.tsx
packages/client/ssr.config.ts
packages/client/ssr.tsx
packages/client/tsconfig.json
packages/client/vite.config.ts
packages/server/index.ts
packages/server/tsconfig.json
yarn.lock

Подготовка клиента для рендера на сервере. 
Настроен Vite для работы express и клиента. 
Базовый роут на сервере для отдачи статической страницы React.

Pix 36 Настроить Express для Server Side Rendering (без Redux, просто отдавать React-страничку)

---

packages/client/src/pages/EndPage/EndPage.tsx
packages/client/src/pages/LeaderBoardPage/LeaderBoardPage.tsx
packages/client/src/processes/GameProcess/GameProcess.tsx
packages/client/src/shared/api/leaderboardApi.ts
packages/client/src/shared/store/store.ts
packages/client/src/shared/types/game.interface.ts
packages/client/src/shared/types/leaderboard.interface.ts
packages/client/src/widgets/Game/logic/GameEngine.ts

PIX-39 Добавить API для лидерборда.

---

packages/client/src/entities/ForumTopic/ui/ForumTopicCard.tsx
packages/client/src/features/ForumTopic/ui/DeleteForumTopic.tsx
packages/client/src/features/ForumTopic/ui/ForumTopicEditor.tsx
packages/client/src/features/ForumTopicComment/ui/ForumTopicAddComment.tsx
packages/client/src/pages/ForumPage/ForumPage.tsx
packages/client/src/pages/ForumTopicPage/ForumTopicPage.tsx
packages/client/src/shared/api/commentApi.ts
packages/client/src/shared/api/topicApi.ts
packages/client/src/shared/store/store.ts
packages/client/src/shared/types/forum-topic.interface.ts
packages/client/src/widgets/ForumTopicCommentList/ui/ForumTopicCommentList.tsx
packages/client/src/widgets/ForumTopicList/ui/ForumTopcList.tsx
packages/server/src/routes/topic.router.ts

Поддержать API форума на клиенте

PIX 48 Поддержать API форума на клиенте

---

packages/server/src/controllers/index.ts
packages/server/src/controllers/topic.controller.ts
packages/server/src/controllers/topicReaction.controller.ts
packages/server/src/helpers/initReactions.ts
packages/server/src/index.ts
packages/server/src/middlewares/auth.ts
packages/server/src/models/index.ts
packages/server/src/models/topic.model.ts
packages/server/src/models/topicReaction.model.ts
packages/server/src/models/userReaction.model.ts
packages/server/src/routes/index.ts
packages/server/src/routes/topicReaction.router.ts
packages/server/src/types/Author.ts
packages/server/src/types/TopicReaction.ts
packages/server/src/types/UserReaction.ts
packages/server/src/types/index.ts

Проектирование и планирование: 
Определение, как эмодзи будут храниться в базе данных. 
Разработка спецификации API для добавления и получения эмодзи-реакций на топик. 
Обновление моделей базы данных: 
Добавление необходимых полей в модель "Reaction" (Реакция), если они ещё не были добавлены. 
Разработка миграции базы данных для применения изменений модели. 
Реализация API для работы с эмодзи: 
Разработка API и контроллеров для добавления эмодзи в качестве реакции на топик.
Разработка API и контроллеров для получения информации об эмодзи-реакциях на топик.

PIX-46 Эмодзи (бэкенд)

---

docker-compose.dev.yml
docker-compose.yml
nginx/Dockerfile
nginx/nginx.conf

Написать конфиг nginx (HTTP2, SSL)

Написать конфиг nginx (HTTP2, SSL)

---

packages/server/package.json
packages/server/src/index.ts
yarn.lock

Добавить защиту от XSS
Проектирование и планирование: 
Определение мест в приложении, где данные от пользователя выводятся на экран (включая сообщения, комментарии, названия топиков и т.д.).
Валидация и экранирование входных данных: 
Реализация строгой валидации всех входных данных, особенно тех, которые могут быть отображены другим пользователям. 
Экранирование специальных символов, таких как "<", ">", "&", которые могут использоваться для ввода HTML или JavaScript-кода.

Добавить защиту от XSS

---

packages/client/src/pages/LeaderBoardPage/LeaderBoardPage.tsx
packages/client/src/shared/api/leaderboardApi.ts
packages/client/src/shared/types/leaderboard.interface.ts

Фикс лидерборда

---

packages/client/src/pages/LoginPage/LoginPage.tsx
packages/client/src/shared/api/authApi.ts

fix(oauth): remove client_id

---

packages/client/src/pages/LoginPage/LoginPage.tsx
packages/client/src/shared/api/authApi.ts

Reverts vairaden/pixel-punch-game#51

Revert "fix(oauth): remove client_id"

---

packages/server/src/controllers/auth.controller.ts

fix(oauth): path fix
